ALTER TABLE [dbo].[M_EMPLOYEE]
    ADD CONSTRAINT [FK_M_EMPLOYEE_M_DEPARTMENT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[M_DEPARTMENT] ([DEPARTMENT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

