ALTER TABLE [dbo].[M_PACKET_ITEM_CAT]
    ADD CONSTRAINT [FK_M_PACKET_ITEM_CAT_M_ITEM_CAT] FOREIGN KEY ([ITEM_CAT_ID]) REFERENCES [dbo].[M_ITEM_CAT] ([ITEM_CAT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

