ALTER TABLE [dbo].[M_ACCOUNT]
    ADD CONSTRAINT [FK_M_ACCOUNT_M_ACCOUNT_CAT] FOREIGN KEY ([ACCOUNT_CAT_ID]) REFERENCES [dbo].[M_ACCOUNT_CAT] ([ACCOUNT_CAT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

