ALTER TABLE [dbo].[T_STOCK_ITEM]
    ADD CONSTRAINT [FK_T_STOCK_ITEM_M_WAREHOUSE] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[M_WAREHOUSE] ([WAREHOUSE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

