ALTER TABLE [dbo].[T_JOURNAL]
    ADD CONSTRAINT [FK_T_JOURNAL_M_COST_CENTER] FOREIGN KEY ([COST_CENTER_ID]) REFERENCES [dbo].[M_COST_CENTER] ([COST_CENTER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

