ALTER TABLE [dbo].[T_REC_ACCOUNT]
    ADD CONSTRAINT [FK_T_REC_ACCOUNT_T_REC_PERIOD] FOREIGN KEY ([REC_PERIOD_ID]) REFERENCES [dbo].[T_REC_PERIOD] ([REC_PERIOD_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

