ALTER TABLE [dbo].[M_ACCOUNT_REF]
    ADD CONSTRAINT [PK_M_ACCOUNT_REF] PRIMARY KEY CLUSTERED ([ACCOUNT_REF_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

