ALTER TABLE [dbo].[M_ITEM_UOM]
    ADD CONSTRAINT [PK_M_ITEM_UOM_1] PRIMARY KEY CLUSTERED ([ITEM_UOM_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

