ALTER TABLE [dbo].[M_ITEM]
    ADD CONSTRAINT [PK_M_ITEM] PRIMARY KEY CLUSTERED ([ITEM_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

