ALTER TABLE [dbo].[M_WAREHOUSE]
    ADD CONSTRAINT [PK_M_WAREHOUSE_1] PRIMARY KEY CLUSTERED ([WAREHOUSE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

