ALTER TABLE [dbo].[M_BRAND]
    ADD CONSTRAINT [PK_M_BRAND_1] PRIMARY KEY CLUSTERED ([BRAND_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

