ALTER TABLE [dbo].[M_DEPARTMENT]
    ADD CONSTRAINT [PK_M_DEPARTMENT] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

