ALTER TABLE [dbo].[REF_ADDRESS]
    ADD CONSTRAINT [PK_M_ADDRESS] PRIMARY KEY CLUSTERED ([ADDRESS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

