ALTER TABLE [dbo].[M_ROOM]
    ADD CONSTRAINT [PK_M_ROOM] PRIMARY KEY CLUSTERED ([ROOM_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

