ALTER TABLE [dbo].[REF_PERSON]
    ADD CONSTRAINT [PK_REF_PERSON] PRIMARY KEY CLUSTERED ([PERSON_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

