ALTER TABLE [dbo].[T_STOCK_CARD]
    ADD CONSTRAINT [PK_T_STOCK_CARD_1] PRIMARY KEY CLUSTERED ([STOCK_CARD_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

