ALTER TABLE [dbo].[T_REFERENCE]
    ADD CONSTRAINT [PK_T_REFERENCE] PRIMARY KEY CLUSTERED ([REFERENCE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

