ALTER TABLE [dbo].[T_TRANS_DET_ITEM]
    ADD CONSTRAINT [PK_T_TRANS_DET_ITEM] PRIMARY KEY CLUSTERED ([TRANS_DET_ITEM_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

