ALTER TABLE [dbo].[T_MENU_ACCESS]
    ADD CONSTRAINT [PK_T_MENU_ACCESS_1] PRIMARY KEY CLUSTERED ([MENU_ACCESS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

