ALTER TABLE [dbo].[T_REC_ACCOUNT]
    ADD CONSTRAINT [PK_T_REC_ACCOUNT] PRIMARY KEY CLUSTERED ([REC_ACCOUNT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

