CREATE TABLE [dbo].[M_ACCOUNT] (
    [ACCOUNT_ID]        NVARCHAR (50)  NOT NULL,
    [ACCOUNT_CAT_ID]    NVARCHAR (50)  NULL,
    [ACCOUNT_PARENT_ID] NVARCHAR (50)  NULL,
    [ACCOUNT_STATUS]    NVARCHAR (50)  NULL,
    [ACCOUNT_NAME]      NVARCHAR (50)  NULL,
    [ACCOUNT_DESC]      NVARCHAR (MAX) NULL,
    [DATA_STATUS]       NVARCHAR (50)  NULL,
    [CREATED_BY]        NVARCHAR (50)  NULL,
    [CREATED_DATE]      DATETIME       NULL,
    [MODIFIED_BY]       NVARCHAR (50)  NULL,
    [MODIFIED_DATE]     DATETIME       NULL,
    [ROW_VERSION]       TIMESTAMP      NULL
);

