CREATE TABLE [dbo].[M_ACCOUNT_REF] (
    [ACCOUNT_REF_ID]  NVARCHAR (50) NOT NULL,
    [REFERENCE_TABLE] NVARCHAR (50) NOT NULL,
    [REFERENCE_TYPE]  NVARCHAR (50) NOT NULL,
    [REFERENCE_ID]    NVARCHAR (50) NOT NULL,
    [ACCOUNT_ID]      NVARCHAR (50) NOT NULL,
    [DATA_STATUS]     NVARCHAR (50) NULL,
    [CREATED_BY]      NVARCHAR (50) NULL,
    [CREATED_DATE]    DATETIME      NULL,
    [MODIFIED_BY]     NVARCHAR (50) NULL,
    [MODIFIED_DATE]   DATETIME      NULL,
    [ROW_VERSION]     TIMESTAMP     NULL
);

