CREATE TABLE [dbo].[M_BRAND] (
    [BRAND_ID]      NVARCHAR (50)  NOT NULL,
    [BRAND_NAME]    NVARCHAR (50)  NOT NULL,
    [BRAND_DESC]    NVARCHAR (MAX) NULL,
    [DATA_STATUS]   NVARCHAR (50)  NULL,
    [CREATED_BY]    NVARCHAR (50)  NULL,
    [CREATED_DATE]  DATETIME       NULL,
    [MODIFIED_BY]   VARCHAR (50)   NULL,
    [MODIFIED_DATE] DATETIME       NULL,
    [ROW_VERSION]   TIMESTAMP      NULL
);

