CREATE TABLE [dbo].[M_ITEM] (
    [ITEM_ID]       NVARCHAR (50)  NOT NULL,
    [ITEM_CAT_ID]   NVARCHAR (50)  NULL,
    [BRAND_ID]      NVARCHAR (50)  NULL,
    [ITEM_NAME]     NVARCHAR (50)  NOT NULL,
    [ITEM_STATUS]   NVARCHAR (50)  NULL,
    [ITEM_PHOTO]    IMAGE          NULL,
    [ITEM_DESC]     NVARCHAR (MAX) NULL,
    [DATA_STATUS]   NVARCHAR (50)  NULL,
    [CREATED_BY]    NVARCHAR (50)  NULL,
    [CREATED_DATE]  DATETIME       NULL,
    [MODIFIED_BY]   NVARCHAR (50)  NULL,
    [MODIFIED_DATE] DATETIME       NULL,
    [ROW_VERSION]   TIMESTAMP      NULL
);

