CREATE TABLE [dbo].[M_PACKET] (
    [PACKET_ID]        NVARCHAR (50)   NOT NULL,
    [PACKET_NAME]      NVARCHAR (50)   NULL,
    [PACKET_PRICE]     DECIMAL (18, 5) NULL,
    [PACKET_PRICE_VIP] DECIMAL (18, 5) NULL,
    [PACKET_STATUS]    NVARCHAR (50)   NULL,
    [PACKET_DESC]      NVARCHAR (50)   NULL,
    [DATA_STATUS]      NVARCHAR (50)   NULL,
    [CREATED_BY]       NVARCHAR (50)   NULL,
    [CREATED_DATE]     DATETIME        NULL,
    [MODIFIED_BY]      NVARCHAR (50)   NULL,
    [MODIFIED_DATE]    DATETIME        NULL,
    [ROW_VERSION]      TIMESTAMP       NULL
);

