CREATE TABLE [dbo].[M_ROOM] (
    [ROOM_ID]       NVARCHAR (50)  NOT NULL,
    [ROOM_NAME]     NVARCHAR (50)  NULL,
    [ROOM_ORDER_NO] INT            NULL,
    [ROOM_TYPE]     NVARCHAR (50)  NULL,
    [ROOM_STATUS]   NVARCHAR (50)  NULL,
    [ROOM_DESC]     NVARCHAR (MAX) NULL,
    [DATA_STATUS]   NVARCHAR (50)  NULL,
    [CREATED_BY]    NVARCHAR (50)  NULL,
    [CREATED_DATE]  DATETIME       NULL,
    [MODIFIED_BY]   NVARCHAR (50)  NULL,
    [MODIFIED_DATE] DATETIME       NULL,
    [ROW_VERSION]   TIMESTAMP      NULL
);

