CREATE TABLE [dbo].[M_WAREHOUSE] (
    [WAREHOUSE_ID]         NVARCHAR (50) NOT NULL,
    [WAREHOUSE_NAME]       NVARCHAR (50) NOT NULL,
    [ADDRESS_ID]           NVARCHAR (50) NULL,
    [COST_CENTER_ID]       NVARCHAR (50) NULL,
    [WAREHOUSE_TYPE]       NVARCHAR (50) NULL,
    [EMPLOYEE_ID]          NVARCHAR (50) NULL,
    [WAREHOUSE_STATUS]     NVARCHAR (50) NULL,
    [WAREHOUSE_IS_DEFAULT] BIT           NULL,
    [WAREHOUSE_PHOTO]      IMAGE         NULL,
    [WAREHOUSE_DESC]       NVARCHAR (50) NULL,
    [DATA_STATUS]          NVARCHAR (50) NULL,
    [CREATED_BY]           NVARCHAR (50) NULL,
    [CREATED_DATE]         DATETIME      NULL,
    [MODIFIED_BY]          NVARCHAR (50) NULL,
    [MODIFIED_DATE]        DATETIME      NULL,
    [ROW_VERSION]          TIMESTAMP     NULL
);

