CREATE TABLE [dbo].[REF_PERSON] (
    [PERSON_ID]           NVARCHAR (50)  NOT NULL,
    [PERSON_FIRST_NAME]   NVARCHAR (50)  NULL,
    [PERSON_LAST_NAME]    NVARCHAR (50)  NULL,
    [PERSON_DOB]          DATETIME       NULL,
    [PERSON_POB]          NVARCHAR (50)  NULL,
    [PERSON_GENDER]       NVARCHAR (50)  NULL,
    [PERSON_PHONE]        NVARCHAR (50)  NULL,
    [PERSON_MOBILE]       NVARCHAR (50)  NULL,
    [PERSON_EMAIL]        NVARCHAR (50)  NULL,
    [PERSON_RELIGION]     NVARCHAR (50)  NULL,
    [PERSON_RACE]         NVARCHAR (50)  NULL,
    [PERSON_ID_CARD_TYPE] NVARCHAR (50)  NULL,
    [PERSON_ID_CARD_NO]   NVARCHAR (50)  NULL,
    [PERSON_DESC]         NVARCHAR (MAX) NULL,
    [DATA_STATUS]         NVARCHAR (50)  NULL,
    [CREATED_BY]          NVARCHAR (50)  NULL,
    [CREATED_DATE]        NCHAR (10)     NULL,
    [MODIFIED_BY]         NVARCHAR (50)  NULL,
    [MODIFIED_DATE]       DATETIME       NULL,
    [ROW_VERSION]         TIMESTAMP      NULL
);

