CREATE TABLE [dbo].[T_JOURNAL_REF] (
    [JOURNAL_REF_ID]   NVARCHAR (50)  NOT NULL,
    [REFERENCE_TABLE]  NVARCHAR (50)  NOT NULL,
    [REFERENCE_TYPE]   NVARCHAR (50)  NOT NULL,
    [REFERENCE_ID]     NVARCHAR (50)  NOT NULL,
    [JOURNAL_ID]       NVARCHAR (50)  NOT NULL,
    [JOURNAL_REF_DESC] NVARCHAR (MAX) NULL,
    [DATA_STATUS]      NVARCHAR (50)  NULL,
    [CREATED_BY]       NVARCHAR (50)  NULL,
    [CREATED_DATE]     DATETIME       NULL,
    [MODIFIED_BY]      NVARCHAR (50)  NULL,
    [MODIFIED_DATE]    DATETIME       NULL,
    [ROW_VERSION]      TIMESTAMP      NULL
);

