CREATE TABLE [dbo].[T_JOURNAL] (
    [JOURNAL_ID]          NVARCHAR (50)   NOT NULL,
    [COST_CENTER_ID]      NVARCHAR (50)   NULL,
    [JOURNAL_TYPE]        NVARCHAR (50)   NULL,
    [JOURNAL_VOUCHER_NO]  NVARCHAR (50)   NULL,
    [JOURNAL_PIC]         NVARCHAR (50)   NULL,
    [JOURNAL_DATE]        DATETIME        NULL,
    [JOURNAL_EVIDENCE_NO] NVARCHAR (50)   NULL,
    [JOURNAL_AMMOUNT]     NUMERIC (18, 5) NULL,
    [JOURNAL_STATUS]      NVARCHAR (50)   NULL,
    [JOURNAL_DESC]        NVARCHAR (MAX)  NULL,
    [DATA_STATUS]         NVARCHAR (50)   NULL,
    [CREATED_BY]          NVARCHAR (50)   NULL,
    [CREATED_DATE]        DATETIME        NULL,
    [MODIFIED_BY]         NVARCHAR (50)   NULL,
    [MODIFIED_DATE]       DATETIME        NULL,
    [ROW_VERSION]         TIMESTAMP       NULL
);

