CREATE TABLE [dbo].[T_REC_ACCOUNT] (
    [REC_ACCOUNT_ID]    NVARCHAR (50)   NOT NULL,
    [REC_PERIOD_ID]     NVARCHAR (50)   NOT NULL,
    [COST_CENTER_ID]    NVARCHAR (50)   NULL,
    [ACCOUNT_ID]        NVARCHAR (50)   NOT NULL,
    [ACCOUNT_STATUS]    NVARCHAR (50)   NULL,
    [REC_ACCOUNT_START] NUMERIC (18, 5) NULL,
    [REC_ACCOUNT_END]   NUMERIC (18, 5) NULL,
    [REC_ACCOUNT_DESC]  NVARCHAR (MAX)  NULL,
    [DATA_STATUS]       NVARCHAR (50)   NULL,
    [CREATED_BY]        NVARCHAR (50)   NULL,
    [CREATED_DATE]      DATETIME        NULL,
    [MODIFIED_BY]       NVARCHAR (50)   NULL,
    [MODIFIED_DATE]     DATETIME        NULL,
    [ROW_VERSION]       TIMESTAMP       NULL
);

