CREATE TABLE [dbo].[T_REC_PERIOD] (
    [REC_PERIOD_ID] NVARCHAR (50)  NOT NULL,
    [PERIOD_FROM]   DATETIME       NOT NULL,
    [PERIOD_TO]     DATETIME       NOT NULL,
    [PERIOD_TYPE]   NVARCHAR (50)  NOT NULL,
    [PERIOD_STATUS] NVARCHAR (50)  NULL,
    [PERIOD_DESC]   NVARCHAR (MAX) NULL,
    [DATA_STATUS]   NVARCHAR (50)  NULL,
    [CREATED_BY]    NVARCHAR (50)  NULL,
    [CREATED_DATE]  DATETIME       NULL,
    [MODIFIED_BY]   NVARCHAR (50)  NULL,
    [MODIFIED_DATE] DATETIME       NULL,
    [ROW_VERSION]   TIMESTAMP      NULL
);

