CREATE TABLE [dbo].[T_STOCK_CARD] (
    [STOCK_CARD_ID]     NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [ITEM_ID]           NVARCHAR (50)   NOT NULL,
    [WAREHOUSE_ID]      NVARCHAR (50)   NOT NULL,
    [TRANS_DET_ID]      NVARCHAR (50)   NULL,
    [STOCK_CARD_DATE]   DATETIME        NULL,
    [STOCK_CARD_STATUS] BIT             NULL,
    [STOCK_CARD_QTY]    NUMERIC (18, 5) NULL,
    [STOCK_CARD_SALDO]  NUMERIC (18, 5) NULL,
    [STOCK_CARD_DESC]   NVARCHAR (MAX)  NULL,
    [DATA_STATUS]       NVARCHAR (50)   NULL,
    [CREATED_BY]        NVARCHAR (50)   NULL,
    [CREATED_DATE]      DATETIME        NULL,
    [MODIFIED_BY]       NVARCHAR (50)   NULL,
    [MODIFIED_DATE]     DATETIME        NULL,
    [ROW_VERSION]       TIMESTAMP       NULL
);

