CREATE TABLE [dbo].[T_STOCK] (
    [STOCK_ID]      NVARCHAR (50)   NOT NULL,
    [ITEM_ID]       NVARCHAR (50)   NOT NULL,
    [WAREHOUSE_ID]  NVARCHAR (50)   NOT NULL,
    [TRANS_DET_ID]  NVARCHAR (50)   NOT NULL,
    [STOCK_DATE]    DATETIME        NULL,
    [STOCK_QTY]     NUMERIC (18, 5) NULL,
    [STOCK_PRICE]   NUMERIC (18, 5) NULL,
    [STOCK_STATUS]  NVARCHAR (50)   NULL,
    [STOCK_DESC]    NVARCHAR (MAX)  NULL,
    [DATA_STATUS]   NVARCHAR (50)   NULL,
    [CREATED_BY]    NVARCHAR (50)   NULL,
    [CREATED_DATE]  DATETIME        NULL,
    [MODIFIED_BY]   NVARCHAR (50)   NULL,
    [MODIFIED_DATE] DATETIME        NULL,
    [ROW_VERSION]   TIMESTAMP       NULL
);

