CREATE TABLE [dbo].[T_STOCK_REF] (
    [STOCK_ID]       NVARCHAR (50)   NOT NULL,
    [STOCK_REF_ID]   NVARCHAR (50)   NOT NULL,
    [STOCK_REF_QTY]  NUMERIC (18, 5) NULL,
    [STOCK_REF_DESC] NVARCHAR (MAX)  NULL,
    [DATA_STATUS]    NVARCHAR (50)   NULL,
    [CREATED_BY]     NVARCHAR (50)   NULL,
    [CREATED_DATE]   DATETIME        NULL,
    [MODIFIED_BY]    NVARCHAR (50)   NULL,
    [MODIFIED_DATE]  DATETIME        NULL,
    [ROW_VERSION]    TIMESTAMP       NULL
);

