CREATE TABLE [dbo].[T_TRANS_DET] (
    [TRANS_DET_ID]    NVARCHAR (50)   NOT NULL,
    [TRANS_ID]        NVARCHAR (50)   NOT NULL,
    [ITEM_ID]         NVARCHAR (50)   NULL,
    [ITEM_UOM_ID]     NVARCHAR (50)   NULL,
    [TRANS_DET_NO]    INT             NULL,
    [TRANS_DET_QTY]   NUMERIC (18, 5) NULL,
    [TRANS_DET_PRICE] NUMERIC (18, 5) NULL,
    [TRANS_DET_DISC]  NUMERIC (18, 5) NULL,
    [TRANS_DET_TOTAL] NUMERIC (18, 5) NULL,
    [TRANS_DET_DESC]  NVARCHAR (MAX)  NULL,
    [DATA_STATUS]     NVARCHAR (50)   NULL,
    [CREATED_BY]      NVARCHAR (50)   NULL,
    [CREATED_DATE]    DATETIME        NULL,
    [MODIFIED_BY]     NVARCHAR (50)   NULL,
    [MODIFIED_DATE]   DATETIME        NULL,
    [ROW_VERSION]     TIMESTAMP       NULL,
    [PACKET_ID]       NVARCHAR (50)   NULL
);

