
CREATE TABLE [dbo].[M_PROMO](
	[PROMO_ID] [nvarchar](50) NOT NULL,
	[PROMO_NAME] [nvarchar](50) NULL,
	[PROMO_START_DATE] [datetime] NULL,
	[PROMO_END_DATE] [datetime] NULL,
	[PROMO_VALUE] [decimal](18, 5) NULL,
	[PROMO_STATUS] [nvarchar](50) NULL,
	[PROMO_DESC] [nvarchar](max) NULL,
	[DATA_STATUS] [nvarchar](50) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[ROW_VERSION] [timestamp] NULL,
 CONSTRAINT [PK_M_PROMO] PRIMARY KEY CLUSTERED 
(
	[PROMO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

alter table  dbo.T_TRANS add 
	PROMO_ID NVARCHAR (50) NULL,
	PROMO_VALUE NUMERIC(18, 5) NULL
;


ALTER TABLE [dbo].[T_TRANS]  WITH CHECK ADD  CONSTRAINT [FK_T_TRANS_M_PROMO] FOREIGN KEY([PROMO_ID])
REFERENCES [dbo].[M_PROMO] ([PROMO_ID])
GO

ALTER TABLE [dbo].[T_TRANS] CHECK CONSTRAINT [FK_T_TRANS_M_PROMO]
GO