CREATE TABLE [dbo].[T_STOCK_REF] (
    [STOCK_ID]       NVARCHAR (50)   NOT NULL,
    [STOCK_REF_ID]   NVARCHAR (50)   NOT NULL,
    [STOCK_REF_QTY]  NUMERIC (18, 5) NULL,
    [STOCK_REF_DESC] NVARCHAR (MAX)  NULL,
    [DATA_STATUS]    NVARCHAR (50)   NULL,
    [CREATED_BY]     NVARCHAR (50)   NULL,
    [CREATED_DATE]   DATETIME        NULL,
    [MODIFIED_BY]    NVARCHAR (50)   NULL,
    [MODIFIED_DATE]  DATETIME        NULL,
    [ROW_VERSION]    TIMESTAMP       NULL
);
go
alter table  [dbo].[T_STOCK_REF] add 
	[STOCK_REF_DATE] DATETIME NULL,
	[STOCK_REF_PRICE] NUMERIC(18, 5) NULL,
	[STOCK_REF_STATUS] NVARCHAR (50) NULL,
	[TRANS_DET_ID] NVARCHAR (50) NULL
;