ALTER TABLE [dbo].[T_TRANS_REF]
	ADD CONSTRAINT [PK_T_TRANS_REF]
	PRIMARY KEY CLUSTERED 
(
	[TRANS_REF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON);